spring:
  application:
    name: "backend"

  datasource:
    url: "jdbc:postgresql://localhost:5432/shop"
    username: "postgres"
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

cors:
  allowed-origins: "http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE"

product:
  url: "https://fakestoreapi.com/products"